[[headers]]
  for = "/.well-known/matrix/client"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/data/resume.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; object-src 'self'; base-uri 'self'; form-action 'self'; img-src https:; frame-ancestors 'none'; font-src 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/presentations/*"
  [headers.values]
    Content-Security-Policy = "default-src *"
