[[headers]]
  for = "/.well-known/matrix/client"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/data/resume.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; style-src 'unsafe-inline'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
