name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9a3a9ade8222dcdf9d3c77710b10df47ee7c7c89
      with:
        submodules: 'recursive'
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Test
      run: npm t
    - name: Build
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
    - name: Audit using Lighthouse
      uses: treosh/lighthouse-ci-action@v3
      with:
        urls: |
          https://mkohler.dev/
        uploadArtifacts: true

  lighthouse:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Audit using Lighthouse
      uses: treosh/lighthouse-ci-action@v3
      with:
        urls: |
          https://mkohler.dev/
        uploadArtifacts: true
