name: Fetch

on:
  schedule:
    # every hour
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
    - name: Fetch
      run: npm run fetch
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_SCOPE_GH_TOKEN }}
    - name: Set Git Author
      run: git config --global user.name "github-actions[bot]"
    - name: Set Git Email
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Commit Changes
      run: git add _data && git commit -m "Update data" || true
    - name: Push
      run: git push origin main
